# Generated by Django 4.2.27 on 2026-06-06 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdSpendDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sku_orders', models.IntegerField(default=0)),
                ('gross_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('gmv', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('orders', models.IntegerField(default=0)),
                ('items_sold', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='COGSItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('sku_variant', models.CharField(blank=True, max_length=128)),
                ('cogs_per_order', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('supplier_ref', models.CharField(blank=True, max_length=64)),
                ('listing_id', models.CharField(blank=True, max_length=32)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('approval', models.CharField(blank=True, default='Y', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['supplier_ref'],
            },
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importer', models.CharField(max_length=32)),
                ('filename', models.CharField(max_length=255)),
                ('rows_added', models.IntegerField(default=0)),
                ('rows_skipped', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(help_text='YYYY-MM', max_length=7, unique=True)),
                ('team_spend', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('software_tools', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monthly_retainers', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('creatify', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('off_platform_1pct', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_ga', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tt_promo_credits', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cost_ship_to_fbt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cost_ship_to_customer', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fbt_hub_placement', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fbt_storage', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fbt_inbound_shipping', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fbt_inbound_incidents', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fbt_booking_noncomp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fbt_routing_noncomp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fbt_outbound_noshow', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fbt_delayed_response', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fbt_disposal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fbt_return_shipping', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fbt_return_seller_handling', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fbt_inbound_return_op', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['month'],
            },
        ),
        migrations.CreateModel(
            name='SettlementRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_created_date', models.DateField(db_index=True, null=True)),
                ('statement_date', models.DateField(null=True)),
                ('order_id', models.CharField(db_index=True, max_length=32)),
                ('settlement_id', models.CharField(max_length=32)),
                ('row_type', models.CharField(db_index=True, max_length=64)),
                ('quantity', models.IntegerField(default=0)),
                ('referral_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('affiliate_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('campaign_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('refund_admin', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fbt_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fbt_reimb', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shipping', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tt_ship_net', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cofunded_promo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('refund_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('chargeback', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('violation', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tt_shop_reimb', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('logistics_reimb', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fbt_warehouse', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fbt_warehouse_comp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rebate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unclassified', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['order_created_date'], name='core_settle_order_c_5d4907_idx'), models.Index(fields=['row_type'], name='core_settle_row_typ_3299a2_idx')],
                'unique_together': {('order_id', 'settlement_id', 'row_type')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=32)),
                ('sku_id', models.CharField(db_index=True, max_length=32)),
                ('created_date', models.DateField(db_index=True)),
                ('quantity', models.IntegerField(default=0)),
                ('status', models.CharField(blank=True, max_length=32)),
                ('gross_sale', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('seller_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('order_refund', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cogs', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['created_date'], name='core_order_created_0b056c_idx')],
                'unique_together': {('order_id', 'sku_id')},
            },
        ),
    ]
