# Generated by Django 4.2.27 on 2026-06-11 23:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_shipping_components'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdLedgerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, help_text='Account balance carried into the start date (pre-window credit).', max_digits=12)),
                ('opening_date', models.DateField(blank=True, help_text='Date the opening balance applies as-of.', null=True)),
                ('opening_discount', models.DecimalField(decimal_places=4, default=Decimal('0.06'), max_digits=5)),
                ('tbsm_default_discount', models.DecimalField(decimal_places=4, default=Decimal('0.06'), help_text='Discount applied to every Others/Increase balance load by default.', max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdLedgerDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('ad_spend', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tbsm_in', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('promo_in', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('card_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('funded', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('full_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('savings_tbsm', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('savings_promo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('funding_source', models.CharField(blank=True, max_length=64)),
                ('discount_on_funded', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('effective_discount', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='AgencyInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(blank=True, max_length=64)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('loaded_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_pct', models.DecimalField(decimal_places=4, default=Decimal('0.06'), max_digits=5)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('entity', models.CharField(blank=True, max_length=128)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='AgencyPromoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('min_amount', models.DecimalField(decimal_places=2, default=10000, help_text='Only the daily-net promo total >= this amount gets tagged; smaller promos stay free.', max_digits=12)),
                ('discount_pct', models.DecimalField(decimal_places=4, default=Decimal('0.10'), max_digits=5)),
                ('note', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='AdTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('txn_time', models.DateTimeField(db_index=True)),
                ('sheet', models.CharField(db_index=True, max_length=16)),
                ('txn_type', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(blank=True, max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('details', models.CharField(blank=True, max_length=255)),
                ('type_label', models.CharField(blank=True, max_length=64)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['txn_time'], name='core_adtran_txn_tim_a64cdb_idx')],
                'unique_together': {('txn_id', 'sheet', 'txn_time', 'amount')},
            },
        ),
    ]
