# Generated by Django 4.2.27 on 2026-06-11 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ad_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='adledgerconfig',
            name='feed_pnl',
            field=models.BooleanField(default=False, help_text='When True, AdLedgerDay TBSM Savings + TT Promo Credits override the manual/zero values on Daily and Monthly P&L. Keep False until the engine is verified against the source exports.'),
        ),
    ]
