# Generated by Django 4.2.27 on 2026-06-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ad_ledger_feed_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_refund',
        ),
        migrations.AddField(
            model_name='settlementrow',
            name='cofunded_promo_campaign_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='settlementrow',
            name='seller_shipping_fee_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
