# Generated by Django 4.2.27 on 2026-06-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_audit_fixes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellershipmentcost',
            name='customer_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='sellershipmentcost',
            name='order_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='sellershipmentcost',
            name='per_pack',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sellershipmentcost',
            name='per_pick',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sellershipmentcost',
            name='product_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sellershipmentcost',
            name='reference_number',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='sellershipmentcost',
            name='shipment_number',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
    ]
